-- Phase 6h-2: clean Belgian-English checklist text
-- Source pdfs were written by French-speaking engineers, so the seeded English
-- carries lots of literal French ('Control' for 'Check', 'pression', 'téléscopic',
-- 'clealiness', 'Measurment', 'hight', 'vacum', etc). This migration replaces
-- those texts in checklist_items in place.
--
-- Safe to re-run: only updates rows whose current text differs from the target.
-- Engineer pass/fail data in case_checklist_item_results keys off item_id, not
-- text, so this is a pure text refresh.

with updates(machine_type, version, section_no, item_no, new_text) as (
  values
    ('DLM'::text, null::text, '1'::text, '1.5'::text, 'Check convex lens holder finger sleeves'::text),
    ('DLM', null, '1', '1.7', 'Check drawer touch button'),
    ('DLM', null, '1', '2.2', 'Run all checks to verify correct operation'),
    ('DLM', null, '2', '2.1', 'Check cleanliness of the LCD glass'),
    ('DLM', null, '2', '2.2', 'Check brightness of the LVDS screen'),
    ('DLM', null, '2', '2.3', 'Check mirror condition'),
    ('DLM', null, '2', '2.4', 'Check motor diaphragm condition'),
    ('DLM', null, '2', '2.5', 'Measurement without lens'),
    ('DLM', null, '3', '3.1', 'Check concave lens holder finger sleeves'),
    ('DLM', null, '3', '3.5', 'Run all checks to verify correct operation'),
    ('DLM', null, '4', '4.1', 'Check state of edged lens holder gripper fingers'),
    ('DLM', null, '4', '4.2', 'Check general state of edged lens holder gripper'),
    ('DLM', null, '4', '4.6', 'Run all checks to verify correct operation'),
    ('MCVP4', null, '1', '1.1', 'Exchange suction cup caps'),
    ('MCVP4', null, '1', '1.2', 'Exchange suction cups'),
    ('MCVP4', null, '1', '1.3', 'Check height locking cylinder'),
    ('MCVP4', null, '1', '1.4', 'Check stops and shock absorber'),
    ('MCVP4', null, '1', '1.5', 'Check chain cable carrier cable'),
    ('MCVP4', null, '1', '1.6', 'Check cylinder play and clean axes'),
    ('MCVP4', null, '1', '1.7', 'Check telescopic suction cup'),
    ('MCVP4', null, '1', '1.8', 'Check and clean venturi filters'),
    ('MCVP4', null, '1', '1.9', 'Exchange the 5 one-way valves'),
    ('MCVP4', null, '1', '1.10', 'Exchange the 5 rubber fingers of the centering gripper'),
    ('MCVP4', null, '1', '1.11', 'Check belt'),
    ('MCVP4', null, '1', '1.12', 'Check finger gripper bearings'),
    ('MCVP4', null, '1', '1.13', 'Check vibration device'),
    ('MCVP4', null, '1', '1.14', 'Check pressure regulators for centering gripper'),
    ('MCVP4', null, '1', '1.15', 'Check condition of the loading platform'),
    ('MCVP4', null, '1', '1.16', 'Check X-Y position and rotation of the platform'),
    ('MCVP4', null, '1', '1.17', 'Check complete loading sequence'),
    ('MCVP4', null, '2', '2.1', 'Check belt tension'),
    ('MCVP4', null, '2', '2.2', 'Check gap of the indexing table'),
    ('MCVP4', null, '2', '2.3', 'Check general condition of grippers'),
    ('MCVP4', null, '2', '2.4', 'Check finger rotation'),
    ('MCVP4', null, '2', '2.5', 'Check gripper opening'),
    ('MCVP4', null, '2', '2.6', 'Check gripper support bearings'),
    ('MCVP4', null, '2', '2.7', 'Check gripper brakes'),
    ('MCVP4', null, '2', '2.8', 'Check solenoid valves'),
    ('MCVP4', null, '3', '3.1', 'Check cleanliness of the LCD glass'),
    ('MCVP4', null, '3', '3.2', 'Check LCD height and level'),
    ('MCVP4', null, '3', '3.3', 'Check LVDS position according to the camera'),
    ('MCVP4', null, '3', '3.4', 'Check LCD polar filter condition'),
    ('MCVP4', null, '3', '3.5', 'Check brightness of the LVDS screen'),
    ('MCVP4', null, '3', '3.6', 'Check condition and cleanliness of the field lens'),
    ('MCVP4', null, '3', '3.7', 'Check polar option'),
    ('MCVP4', null, '3', '3.8', 'Check condition and cleanliness of the additional lens'),
    ('MCVP4', null, '3', '3.9', 'Check camera focus'),
    ('MCVP4', null, '3', '3.10', 'Check motor diaphragm condition'),
    ('MCVP4', null, '3', '3.11', 'Check couplings'),
    ('MCVP4', null, '3', '3.12', 'Check X,Y tables'),
    ('MCVP4', null, '3', '3.13', 'Check shaft wear condition'),
    ('MCVP4', null, '3', '3.14', 'Check shaft tightening'),
    ('MCVP4', null, '3', '3.15', 'Check motor cables'),
    ('MCVP4', null, '3', '3.16', 'Check pressure regulator'),
    ('MCVP4', null, '3', '3.17', 'Check cylinder play and clean axes'),
    ('MCVP4', null, '4', '4.1', 'Check push buttons and indicator lamps'),
    ('MCVP4', null, '4', '4.2', 'Check lamp voltage presence'),
    ('MCVP4', null, '4', '4.3', 'Check light tower'),
    ('MCVP4', null, '4', '4.4', 'Check door detectors'),
    ('MCVP4', null, '4', '4.5', 'Check fans and filters'),
    ('MCVP4', null, '4', '4.6', 'Check filter and speed of the filter group'),
    ('MCVP4', null, '4', '4.7', 'General cleaning of the machine'),
    ('MCVP4', null, '5', '5.1', 'Check cleanliness of the lens heads'),
    ('MCVP4', null, '5', '5.2', 'Check alignment of the heads'),
    ('MCVP4', null, '5', '5.3', 'Check homing height'),
    ('MCVP4', null, '5', '5.4', 'Check signal interference'),
    ('MCVP4', null, '5', '5.5', 'Check signals in general'),
    ('MCVP4', null, '5', '5.6', 'Test of 1000 measurements'),
    ('MCVP4', null, '6', '6.1', 'Clean PC filters and the frame'),
    ('MCVP4', null, '6', '6.2', 'Check UPS battery'),
    ('MCVP4', null, '7', '7.1', 'Check cleanliness of the LCD glass'),
    ('MCVP4', null, '7', '7.2', 'Check brightness of the LVDS screen'),
    ('MCVP4', null, '7', '7.3', 'Check mirror condition'),
    ('MCVP4', null, '7', '7.4', 'Check motor diaphragm condition'),
    ('MCVP4', null, '7', '7.5', 'Measurement without lens'),
    ('MCVP4', null, '8', '8.1', 'Exchange suction cup cap'),
    ('MCVP4', null, '8', '8.2', 'Exchange suction cup'),
    ('MCVP4', null, '8', '8.3', 'Check chain cable carrier cable'),
    ('MCVP4', null, '8', '8.4', 'For V1: check cylinder play and clean axes'),
    ('MCVP4', null, '8', '8.5', 'For V2: check belt of the electric cylinder'),
    ('MCVP4', null, '8', '8.6', 'Check telescopic suction cup'),
    ('MCVP4', null, '8', '8.7', 'Check and clean venturi filters'),
    ('MCVP4', null, '9', '9.1', 'Check state of shaft wear'),
    ('MCVP4', null, '9', '9.2', 'Check cone condition'),
    ('MCVP4', null, '9', '9.3', 'Check shaft tightening'),
    ('MCVP4', null, '9', '9.4', 'Check motor cables'),
    ('MCVP4', null, '9', '9.5', 'Check pressure regulator'),
    ('MCVP4', null, '9', '9.6', 'Check cylinder play'),
    ('MCVP4', null, '10', '10.1', 'Check chain'),
    ('MCVP4', null, '10', '10.2', 'Check pad brake cylinder'),
    ('MCVP4', null, '10', '10.3', 'Check bar code reader'),
    ('MCVP4', null, '10', '10.4', 'Check stop tray'),
    ('MCVP4', null, '10', '10.5', 'Check detectors and reflector'),
    ('MCVP4', null, '11', '11.1', 'Cleaning device'),
    ('MCVP4', null, '11', '11.2', 'Check state of the printer head'),
    ('MCVP8', 'V1', '1', '1.1', 'Exchange suction cup caps'),
    ('MCVP8', 'V1', '1', '1.2', 'Check telescopic cylinder'),
    ('MCVP8', 'V1', '1', '1.3', 'Check play of the telescopic cylinder'),
    ('MCVP8', 'V1', '1', '1.4', 'Check stops and shock absorber'),
    ('MCVP8', 'V1', '1', '1.5', 'Check chain cable carrier cable'),
    ('MCVP8', 'V1', '1', '1.6', 'Check rubber covering on the loading platform'),
    ('MCVP8', 'V1', '1', '1.7', 'Check gripper and dampers'),
    ('MCVP8', 'V1', '1', '1.8', 'Clean the vacuum filter of venturi and tubing'),
    ('MCVP8', 'V1', '1', '1.10', 'Check diameter gripper'),
    ('MCVP8', 'V1', '2', '2.1', 'Check brake pressure and brake membranes'),
    ('MCVP8', 'V1', '2', '2.2', 'Check gripper and refurbishment according to part availability'),
    ('MCVP8', 'V1', '2', '2.3', 'Lubrication of the carrier'),
    ('MCVP8', 'V1', '2', '2.4', 'Check cone'),
    ('MCVP8', 'V1', '2', '2.5', 'Check cannelure'),
    ('MCVP8', 'V1', '2', '2.6', 'Check cone and shaft correspondence'),
    ('MCVP8', 'V1', '3', '3.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V1', '3', '3.2', 'Check LCD height and level'),
    ('MCVP8', 'V1', '3', '3.3', 'Check LCD position according to the camera'),
    ('MCVP8', 'V1', '3', '3.4', 'Check LCD polar filter condition'),
    ('MCVP8', 'V1', '3', '3.5', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V1', '3', '3.6', 'Check condition and cleanliness of the field lens'),
    ('MCVP8', 'V1', '3', '3.7', 'Check polar option'),
    ('MCVP8', 'V1', '3', '3.8', 'Check condition and cleanliness of the additional lens'),
    ('MCVP8', 'V1', '3', '3.9', 'Check camera focus'),
    ('MCVP8', 'V1', '3', '3.10', 'Check motor diaphragm condition'),
    ('MCVP8', 'V1', '3', '3.11', 'Check couplings'),
    ('MCVP8', 'V1', '3', '3.12', 'Check X,Y tables'),
    ('MCVP8', 'V1', '3', '3.13', 'Check shaft wear condition'),
    ('MCVP8', 'V1', '3', '3.14', 'Check shaft tightening'),
    ('MCVP8', 'V1', '3', '3.15', 'Check motor cables'),
    ('MCVP8', 'V1', '3', '3.16', 'Check pressure regulator'),
    ('MCVP8', 'V1', '3', '3.17', 'Check cylinder play and clean axes'),
    ('MCVP8', 'V1', '4', '4.1', 'Check push buttons and indicator lamps'),
    ('MCVP8', 'V1', '4', '4.2', 'Check lamp voltage presence'),
    ('MCVP8', 'V1', '4', '4.3', 'Check light tower'),
    ('MCVP8', 'V1', '4', '4.4', 'Check security'),
    ('MCVP8', 'V1', '4', '4.5', 'Check fans and filters'),
    ('MCVP8', 'V1', '4', '4.6', 'Check filter and speed of the filter group'),
    ('MCVP8', 'V1', '4', '4.7', 'General cleaning of the machine'),
    ('MCVP8', 'V1', '5', '5.1', 'Check cleanliness of the lens heads'),
    ('MCVP8', 'V1', '5', '5.2', 'Check alignment of the heads'),
    ('MCVP8', 'V1', '5', '5.3', 'Check homing height'),
    ('MCVP8', 'V1', '5', '5.4', 'Check signal interference'),
    ('MCVP8', 'V1', '5', '5.5', 'Check signals in general'),
    ('MCVP8', 'V1', '5', '5.6', 'Test of 1000 measurements'),
    ('MCVP8', 'V1', '6', '6.1', 'Clean PC filters and the frame'),
    ('MCVP8', 'V1', '6', '6.2', 'Check UPS battery'),
    ('MCVP8', 'V1', '7', '7.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V1', '7', '7.2', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V1', '7', '7.3', 'Check mirror condition'),
    ('MCVP8', 'V1', '7', '7.4', 'Check motor diaphragm condition'),
    ('MCVP8', 'V1', '7', '7.5', 'Measurement without lens'),
    ('MCVP8', 'V1', '8', '8.1', 'Check shaft wear condition'),
    ('MCVP8', 'V1', '8', '8.2', 'Check shaft tightening'),
    ('MCVP8', 'V1', '8', '8.3', 'Check motor cables'),
    ('MCVP8', 'V1', '8', '8.4', 'Check pressure regulator'),
    ('MCVP8', 'V1', '8', '8.5', 'Check cylinder play and clean axes'),
    ('MCVP8', 'V1', '8', '8.6', 'Check additional prism'),
    ('MCVP8', 'V1', '8', '8.7', 'Check couplings'),
    ('MCVP8', 'V1', '8', '8.9', 'Check X, Y tables'),
    ('MCVP8', 'V1', '8', '8.10', 'Check ball screw of the fixed axes'),
    ('MCVP8', 'V1', '8', '8.11', 'Check truck and Star guide'),
    ('MCVP8', 'V1', '8', '8.14', 'Check optical alignment'),
    ('MCVP8', 'V1', '9', '9.1', 'Check rotary switch for transmission and reflection'),
    ('MCVP8', 'V1', '9', '9.3', 'Check lamps and clean reflectors'),
    ('MCVP8', 'V1', '9', '9.4', 'Check UV LED'),
    ('MCVP8', 'V1', '9', '9.5', 'Check bright and dark calibration'),
    ('MCVP8', 'V1', '11', '11.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V1', '11', '11.2', 'Check LCD height and level'),
    ('MCVP8', 'V1', '11', '11.3', 'Check LVDS position according to the camera'),
    ('MCVP8', 'V1', '11', '11.4', 'Check LCD polar filter condition'),
    ('MCVP8', 'V1', '11', '11.5', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V1', '11', '11.6', 'Check condition and cleanliness of the field lens'),
    ('MCVP8', 'V1', '11', '11.7', 'Check camera focus'),
    ('MCVP8', 'V1', '11', '11.8', 'Check motor diaphragm condition'),
    ('MCVP8', 'V1', '11', '11.9', 'Calibration of the motor diaphragm aperture'),
    ('MCVP8', 'V1', '12', '12.1', 'Exchange suction cup cap'),
    ('MCVP8', 'V1', '12', '12.3', 'Check chain cable carrier cable'),
    ('MCVP8', 'V1', '12', '12.4', 'For V1: check cylinder play and clean axes'),
    ('MCVP8', 'V1', '12', '12.5', 'For V2: check belt of the electric cylinder'),
    ('MCVP8', 'V1', '12', '12.6', 'Check telescopic suction cup'),
    ('MCVP8', 'V1', '12', '12.7', 'Check and clean venturi filters'),
    ('MCVP8', 'V1', '13', '13.1', 'Check state of shaft wear'),
    ('MCVP8', 'V1', '13', '13.2', 'Check cone condition'),
    ('MCVP8', 'V1', '13', '13.3', 'Check shaft tightening'),
    ('MCVP8', 'V1', '13', '13.4', 'Check motor cables'),
    ('MCVP8', 'V1', '13', '13.5', 'Check pressure regulator'),
    ('MCVP8', 'V1', '13', '13.6', 'Check cylinder play'),
    ('MCVP8', 'V1', '14', '14.1', 'Check chain'),
    ('MCVP8', 'V1', '14', '14.2', 'Check and clean the bar code reader'),
    ('MCVP8', 'V1', '14', '14.3', 'Check stop tray'),
    ('MCVP8', 'V1', '14', '14.4', 'Check detectors and reflector'),
    ('MCVP8', 'V1', '15', '15.1', 'Check all shock absorbers'),
    ('MCVP8', 'V1', '15', '15.2', 'Check condition of the pusher and guiding plates'),
    ('MCVP8', 'V1', '15', '15.3', 'Cleaning of the platforms and adjustment if required'),
    ('MCVP8', 'V1', '16', '16.1', 'Cleaning device'),
    ('MCVP8', 'V1', '16', '16.2', 'Check state of the printer head'),
    ('MCVP8', 'V1', '16', '17.1', 'Check state of the UV lamp'),
    ('MCVP8', 'V1', '16', '17.2', 'Check 0 degree inclination'),
    ('MCVP8', 'V1', '16', '18.1', 'Check robot belt'),
    ('MCVP8', 'V1', '16', '18.2', 'Replace the battery'),
    ('MCVP8', 'V1', '16', '18.4', 'Check all air tubes and cables'),
    ('MCVP8', 'V1', '16', '19.1', 'Check smoothness of the piston'),
    ('MCVP8', 'V1', '16', '19.2', 'Check tightness of motor coupling screws'),
    ('MCVP8', 'V1', '20', '20.2', 'Check station-to-station alignment (CALI30)'),
    ('MCVP8', 'V2', '1', '1.1', 'Exchange suction cup caps'),
    ('MCVP8', 'V2', '1', '1.2', 'Exchange suction cups'),
    ('MCVP8', 'V2', '1', '1.3', 'Check height locking cylinder'),
    ('MCVP8', 'V2', '1', '1.4', 'Check stops and shock absorber'),
    ('MCVP8', 'V2', '1', '1.5', 'Check chain cable carrier cable'),
    ('MCVP8', 'V2', '1', '1.6', 'Check cylinder play and clean axes'),
    ('MCVP8', 'V2', '1', '1.7', 'Check telescopic suction cup'),
    ('MCVP8', 'V2', '1', '1.8', 'Check and clean venturi filters'),
    ('MCVP8', 'V2', '1', '1.9', 'Exchange the 5 one-way valves'),
    ('MCVP8', 'V2', '1', '1.10', 'Exchange the 5 rubber fingers of the centering gripper'),
    ('MCVP8', 'V2', '1', '1.11', 'Check belt'),
    ('MCVP8', 'V2', '1', '1.12', 'Check finger gripper bearings'),
    ('MCVP8', 'V2', '1', '1.13', 'Check vibration device'),
    ('MCVP8', 'V2', '1', '1.14', 'Check pressure regulators for centering gripper'),
    ('MCVP8', 'V2', '1', '1.15', 'Check condition of the loading platform'),
    ('MCVP8', 'V2', '1', '1.16', 'Check X-Y position and rotation of the platform'),
    ('MCVP8', 'V2', '1', '1.17', 'Check complete loading sequence'),
    ('MCVP8', 'V2', '2', '2.1', 'Check belt tension'),
    ('MCVP8', 'V2', '2', '2.2', 'Check gap of the indexing table'),
    ('MCVP8', 'V2', '2', '2.3', 'Check general condition of grippers'),
    ('MCVP8', 'V2', '2', '2.4', 'Check finger rotation'),
    ('MCVP8', 'V2', '2', '2.5', 'Check gripper opening'),
    ('MCVP8', 'V2', '2', '2.6', 'Check gripper support bearings'),
    ('MCVP8', 'V2', '2', '2.7', 'Check gripper brakes'),
    ('MCVP8', 'V2', '2', '2.8', 'Check solenoid valves'),
    ('MCVP8', 'V2', '3', '3.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V2', '3', '3.2', 'Check LCD height and level'),
    ('MCVP8', 'V2', '3', '3.3', 'Check LCD position according to the camera'),
    ('MCVP8', 'V2', '3', '3.4', 'Check LCD polar filter condition'),
    ('MCVP8', 'V2', '3', '3.5', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V2', '3', '3.6', 'Check condition and cleanliness of the field lens'),
    ('MCVP8', 'V2', '3', '3.7', 'Check polar option'),
    ('MCVP8', 'V2', '3', '3.8', 'Check condition and cleanliness of the additional lens'),
    ('MCVP8', 'V2', '3', '3.9', 'Check camera focus'),
    ('MCVP8', 'V2', '3', '3.10', 'Check motor diaphragm condition'),
    ('MCVP8', 'V2', '3', '3.11', 'Check couplings'),
    ('MCVP8', 'V2', '3', '3.12', 'Check X,Y tables'),
    ('MCVP8', 'V2', '3', '3.13', 'Check shaft wear condition'),
    ('MCVP8', 'V2', '3', '3.14', 'Check shaft tightening'),
    ('MCVP8', 'V2', '3', '3.15', 'Check motor cables'),
    ('MCVP8', 'V2', '3', '3.16', 'Check pressure regulator'),
    ('MCVP8', 'V2', '3', '3.17', 'Check cylinder play and clean axes'),
    ('MCVP8', 'V2', '4', '4.1', 'Check push buttons and indicator lamps'),
    ('MCVP8', 'V2', '4', '4.2', 'Check lamp voltage presence'),
    ('MCVP8', 'V2', '4', '4.3', 'Check light tower'),
    ('MCVP8', 'V2', '4', '4.4', 'Check door detectors'),
    ('MCVP8', 'V2', '4', '4.5', 'Check fans and filters'),
    ('MCVP8', 'V2', '4', '4.6', 'Check filter and speed of the filter group'),
    ('MCVP8', 'V2', '4', '4.7', 'General cleaning of the machine'),
    ('MCVP8', 'V2', '5', '5.1', 'Check cleanliness of the lens heads'),
    ('MCVP8', 'V2', '5', '5.2', 'Check alignment of the heads'),
    ('MCVP8', 'V2', '5', '5.3', 'Check homing height'),
    ('MCVP8', 'V2', '5', '5.4', 'Check signal interference'),
    ('MCVP8', 'V2', '5', '5.5', 'Check signals in general'),
    ('MCVP8', 'V2', '5', '5.6', 'Test of 1000 measurements'),
    ('MCVP8', 'V2', '6', '6.1', 'Clean PC filters and the frame'),
    ('MCVP8', 'V2', '6', '6.2', 'Check UPS battery'),
    ('MCVP8', 'V2', '7', '7.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V2', '7', '7.2', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V2', '7', '7.3', 'Check mirror condition'),
    ('MCVP8', 'V2', '7', '7.4', 'Check motor diaphragm condition'),
    ('MCVP8', 'V2', '7', '7.5', 'Measurement without lens'),
    ('MCVP8', 'V2', '8', '8.1', 'Check shaft wear condition'),
    ('MCVP8', 'V2', '8', '8.2', 'Check shaft tightening'),
    ('MCVP8', 'V2', '8', '8.3', 'Check motor cables'),
    ('MCVP8', 'V2', '8', '8.4', 'Check pressure regulator'),
    ('MCVP8', 'V2', '8', '8.5', 'Check cylinder play and clean axes'),
    ('MCVP8', 'V2', '8', '8.6', 'Check additional prism'),
    ('MCVP8', 'V2', '8', '8.7', 'Check couplings'),
    ('MCVP8', 'V2', '8', '8.9', 'Check X, Y tables'),
    ('MCVP8', 'V2', '8', '8.10', 'Check ball screw of the fixed axes'),
    ('MCVP8', 'V2', '8', '8.11', 'Check truck and Star guide'),
    ('MCVP8', 'V2', '8', '8.14', 'Check optical alignment'),
    ('MCVP8', 'V2', '9', '9.1', 'Check rotary switch for transmission and reflection'),
    ('MCVP8', 'V2', '9', '9.3', 'Check lamps and clean reflectors'),
    ('MCVP8', 'V2', '9', '9.4', 'Check UV LED'),
    ('MCVP8', 'V2', '9', '9.5', 'Check bright and dark calibration'),
    ('MCVP8', 'V2', '10', '10.2', 'Remove dust with a vacuum cleaner, clean with a suitable product and cloth'),
    ('MCVP8', 'V2', '10', '10.5', 'Check cleanliness of whole system'),
    ('MCVP8', 'V2', '10', '10.12', 'Check the status (visual) of flat cable; exchange if the flat seems damaged'),
    ('MCVP8', 'V2', '10', '10.13', 'Check cleanliness of the head'),
    ('MCVP8', 'V2', '10', '10.15', 'Check axis alignment'),
    ('MCVP8', 'V2', '10', '10.16', 'Check and adjust double layout'),
    ('MCVP8', 'V2', '11', '11.1', 'Check cleanliness of the LCD glass'),
    ('MCVP8', 'V2', '11', '11.2', 'Check LCD height and level'),
    ('MCVP8', 'V2', '11', '11.3', 'Check LVDS position according to the camera'),
    ('MCVP8', 'V2', '11', '11.4', 'Check LCD polar filter condition'),
    ('MCVP8', 'V2', '11', '11.5', 'Check brightness of the LVDS screen'),
    ('MCVP8', 'V2', '11', '11.6', 'Check condition and cleanliness of the field lens'),
    ('MCVP8', 'V2', '11', '11.7', 'Check camera focus'),
    ('MCVP8', 'V2', '11', '11.8', 'Check motor diaphragm condition'),
    ('MCVP8', 'V2', '11', '11.9', 'Calibration of the motor diaphragm aperture'),
    ('MCVP8', 'V2', '12', '12.1', 'Exchange suction cup cap'),
    ('MCVP8', 'V2', '12', '12.2', 'Exchange suction cup'),
    ('MCVP8', 'V2', '12', '12.3', 'Check chain cable carrier cable'),
    ('MCVP8', 'V2', '12', '12.4', 'For V1: check cylinder play and clean axes'),
    ('MCVP8', 'V2', '12', '12.5', 'For V2: check belt of the electric cylinder'),
    ('MCVP8', 'V2', '12', '12.6', 'Check telescopic suction cup'),
    ('MCVP8', 'V2', '12', '12.7', 'Check and clean venturi filters'),
    ('MCVP8', 'V2', '13', '13.1', 'Check state of shaft wear'),
    ('MCVP8', 'V2', '13', '13.2', 'Check cone condition'),
    ('MCVP8', 'V2', '13', '13.3', 'Check shaft tightening'),
    ('MCVP8', 'V2', '13', '13.4', 'Check motor cables'),
    ('MCVP8', 'V2', '13', '13.5', 'Check pressure regulator'),
    ('MCVP8', 'V2', '13', '13.6', 'Check cylinder play'),
    ('MCVP8', 'V2', '14', '14.1', 'Check chain'),
    ('MCVP8', 'V2', '14', '14.2', 'Check pad brake cylinder'),
    ('MCVP8', 'V2', '14', '14.3', 'Check bar code reader'),
    ('MCVP8', 'V2', '14', '14.4', 'Check stop tray'),
    ('MCVP8', 'V2', '14', '14.5', 'Check detectors and reflector'),
    ('MCVP8', 'V2', '15', '15.1', 'Cleaning device'),
    ('MCVP8', 'V2', '15', '15.2', 'Check state of the printer head'),
    ('SPV2', null, '1', '1.6', 'Check communication of the printer and the thickness measurement'),
    ('SPV2', null, '3', '3.6', 'Check different visualization holders'),
    ('SPV2', null, '3', '3.7', 'Check LEDs and fibers for the visualization'),
    ('SPV2', null, '4', '4.4', 'Check marking position according to dimension calibration'),
    ('SPV2', null, '7', '7.2', 'Check the adjustment'),
    ('SPV3', null, '1', '1.6', 'Check communication of the printer and the thickness measurement'),
    ('SPV3', null, '3', '3.6', 'Check different visualization holders'),
    ('SPV3', null, '3', '3.7', 'Check LEDs and fibers for the visualization'),
    ('SPV3', null, '4', '4.4', 'Check marking position according to dimension calibration'),
    ('SPV3', null, '7', '7.2', 'Check the adjustment')
)
update checklist_items i
set text = u.new_text
from checklist_sections s, checklist_templates t, updates u
where i.section_id = s.id
  and s.template_id = t.id
  and t.machine_type = u.machine_type
  and t.version is not distinct from u.version
  and s.section_no = u.section_no
  and i.item_no = u.item_no
  and i.text <> u.new_text;
